package com.service.domain;

public class Auth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_id
     *
     * @mbggenerated
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_name
     *
     * @mbggenerated
     */
    private String authName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_path
     *
     * @mbggenerated
     */
    private String authPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_code
     *
     * @mbggenerated
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_disc
     *
     * @mbggenerated
     */
    private String authDisc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_shorthand
     *
     * @mbggenerated
     */
    private String authShorthand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_sh
     *
     * @mbggenerated
     */
    private String authSh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_ad
     *
     * @mbggenerated
     */
    private String authAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_rm
     *
     * @mbggenerated
     */
    private String authRm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_md
     *
     * @mbggenerated
     */
    private String authMd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_se
     *
     * @mbggenerated
     */
    private String authSe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_im
     *
     * @mbggenerated
     */
    private String authIm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_ex
     *
     * @mbggenerated
     */
    private String authEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_pr
     *
     * @mbggenerated
     */
    private String authPr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_auth.auth_dis_flag
     *
     * @mbggenerated
     */
    private String authDisFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_id
     *
     * @return the value of tab_auth.auth_id
     *
     * @mbggenerated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_id
     *
     * @param authId the value for tab_auth.auth_id
     *
     * @mbggenerated
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_name
     *
     * @return the value of tab_auth.auth_name
     *
     * @mbggenerated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_name
     *
     * @param authName the value for tab_auth.auth_name
     *
     * @mbggenerated
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_path
     *
     * @return the value of tab_auth.auth_path
     *
     * @mbggenerated
     */
    public String getAuthPath() {
        return authPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_path
     *
     * @param authPath the value for tab_auth.auth_path
     *
     * @mbggenerated
     */
    public void setAuthPath(String authPath) {
        this.authPath = authPath == null ? null : authPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_code
     *
     * @return the value of tab_auth.auth_code
     *
     * @mbggenerated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_code
     *
     * @param authCode the value for tab_auth.auth_code
     *
     * @mbggenerated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_disc
     *
     * @return the value of tab_auth.auth_disc
     *
     * @mbggenerated
     */
    public String getAuthDisc() {
        return authDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_disc
     *
     * @param authDisc the value for tab_auth.auth_disc
     *
     * @mbggenerated
     */
    public void setAuthDisc(String authDisc) {
        this.authDisc = authDisc == null ? null : authDisc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_shorthand
     *
     * @return the value of tab_auth.auth_shorthand
     *
     * @mbggenerated
     */
    public String getAuthShorthand() {
        return authShorthand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_shorthand
     *
     * @param authShorthand the value for tab_auth.auth_shorthand
     *
     * @mbggenerated
     */
    public void setAuthShorthand(String authShorthand) {
        this.authShorthand = authShorthand == null ? null : authShorthand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_sh
     *
     * @return the value of tab_auth.auth_sh
     *
     * @mbggenerated
     */
    public String getAuthSh() {
        return authSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_sh
     *
     * @param authSh the value for tab_auth.auth_sh
     *
     * @mbggenerated
     */
    public void setAuthSh(String authSh) {
        this.authSh = authSh == null ? null : authSh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_ad
     *
     * @return the value of tab_auth.auth_ad
     *
     * @mbggenerated
     */
    public String getAuthAd() {
        return authAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_ad
     *
     * @param authAd the value for tab_auth.auth_ad
     *
     * @mbggenerated
     */
    public void setAuthAd(String authAd) {
        this.authAd = authAd == null ? null : authAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_rm
     *
     * @return the value of tab_auth.auth_rm
     *
     * @mbggenerated
     */
    public String getAuthRm() {
        return authRm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_rm
     *
     * @param authRm the value for tab_auth.auth_rm
     *
     * @mbggenerated
     */
    public void setAuthRm(String authRm) {
        this.authRm = authRm == null ? null : authRm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_md
     *
     * @return the value of tab_auth.auth_md
     *
     * @mbggenerated
     */
    public String getAuthMd() {
        return authMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_md
     *
     * @param authMd the value for tab_auth.auth_md
     *
     * @mbggenerated
     */
    public void setAuthMd(String authMd) {
        this.authMd = authMd == null ? null : authMd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_se
     *
     * @return the value of tab_auth.auth_se
     *
     * @mbggenerated
     */
    public String getAuthSe() {
        return authSe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_se
     *
     * @param authSe the value for tab_auth.auth_se
     *
     * @mbggenerated
     */
    public void setAuthSe(String authSe) {
        this.authSe = authSe == null ? null : authSe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_im
     *
     * @return the value of tab_auth.auth_im
     *
     * @mbggenerated
     */
    public String getAuthIm() {
        return authIm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_im
     *
     * @param authIm the value for tab_auth.auth_im
     *
     * @mbggenerated
     */
    public void setAuthIm(String authIm) {
        this.authIm = authIm == null ? null : authIm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_ex
     *
     * @return the value of tab_auth.auth_ex
     *
     * @mbggenerated
     */
    public String getAuthEx() {
        return authEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_ex
     *
     * @param authEx the value for tab_auth.auth_ex
     *
     * @mbggenerated
     */
    public void setAuthEx(String authEx) {
        this.authEx = authEx == null ? null : authEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_pr
     *
     * @return the value of tab_auth.auth_pr
     *
     * @mbggenerated
     */
    public String getAuthPr() {
        return authPr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_pr
     *
     * @param authPr the value for tab_auth.auth_pr
     *
     * @mbggenerated
     */
    public void setAuthPr(String authPr) {
        this.authPr = authPr == null ? null : authPr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_auth.auth_dis_flag
     *
     * @return the value of tab_auth.auth_dis_flag
     *
     * @mbggenerated
     */
    public String getAuthDisFlag() {
        return authDisFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_auth.auth_dis_flag
     *
     * @param authDisFlag the value for tab_auth.auth_dis_flag
     *
     * @mbggenerated
     */
    public void setAuthDisFlag(String authDisFlag) {
        this.authDisFlag = authDisFlag == null ? null : authDisFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Auth other = (Auth) that;
        return (this.getAuthId() == null ? other.getAuthId() == null : this.getAuthId().equals(other.getAuthId()))
            && (this.getAuthName() == null ? other.getAuthName() == null : this.getAuthName().equals(other.getAuthName()))
            && (this.getAuthPath() == null ? other.getAuthPath() == null : this.getAuthPath().equals(other.getAuthPath()))
            && (this.getAuthCode() == null ? other.getAuthCode() == null : this.getAuthCode().equals(other.getAuthCode()))
            && (this.getAuthDisc() == null ? other.getAuthDisc() == null : this.getAuthDisc().equals(other.getAuthDisc()))
            && (this.getAuthShorthand() == null ? other.getAuthShorthand() == null : this.getAuthShorthand().equals(other.getAuthShorthand()))
            && (this.getAuthSh() == null ? other.getAuthSh() == null : this.getAuthSh().equals(other.getAuthSh()))
            && (this.getAuthAd() == null ? other.getAuthAd() == null : this.getAuthAd().equals(other.getAuthAd()))
            && (this.getAuthRm() == null ? other.getAuthRm() == null : this.getAuthRm().equals(other.getAuthRm()))
            && (this.getAuthMd() == null ? other.getAuthMd() == null : this.getAuthMd().equals(other.getAuthMd()))
            && (this.getAuthSe() == null ? other.getAuthSe() == null : this.getAuthSe().equals(other.getAuthSe()))
            && (this.getAuthIm() == null ? other.getAuthIm() == null : this.getAuthIm().equals(other.getAuthIm()))
            && (this.getAuthEx() == null ? other.getAuthEx() == null : this.getAuthEx().equals(other.getAuthEx()))
            && (this.getAuthPr() == null ? other.getAuthPr() == null : this.getAuthPr().equals(other.getAuthPr()))
            && (this.getAuthDisFlag() == null ? other.getAuthDisFlag() == null : this.getAuthDisFlag().equals(other.getAuthDisFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAuthId() == null) ? 0 : getAuthId().hashCode());
        result = prime * result + ((getAuthName() == null) ? 0 : getAuthName().hashCode());
        result = prime * result + ((getAuthPath() == null) ? 0 : getAuthPath().hashCode());
        result = prime * result + ((getAuthCode() == null) ? 0 : getAuthCode().hashCode());
        result = prime * result + ((getAuthDisc() == null) ? 0 : getAuthDisc().hashCode());
        result = prime * result + ((getAuthShorthand() == null) ? 0 : getAuthShorthand().hashCode());
        result = prime * result + ((getAuthSh() == null) ? 0 : getAuthSh().hashCode());
        result = prime * result + ((getAuthAd() == null) ? 0 : getAuthAd().hashCode());
        result = prime * result + ((getAuthRm() == null) ? 0 : getAuthRm().hashCode());
        result = prime * result + ((getAuthMd() == null) ? 0 : getAuthMd().hashCode());
        result = prime * result + ((getAuthSe() == null) ? 0 : getAuthSe().hashCode());
        result = prime * result + ((getAuthIm() == null) ? 0 : getAuthIm().hashCode());
        result = prime * result + ((getAuthEx() == null) ? 0 : getAuthEx().hashCode());
        result = prime * result + ((getAuthPr() == null) ? 0 : getAuthPr().hashCode());
        result = prime * result + ((getAuthDisFlag() == null) ? 0 : getAuthDisFlag().hashCode());
        return result;
    }
}