package com.service.domain;

import java.util.ArrayList;
import java.util.List;

public class AuthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public AuthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAuthIdIsNull() {
            addCriterion("auth_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthIdIsNotNull() {
            addCriterion("auth_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthIdEqualTo(String value) {
            addCriterion("auth_id =", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotEqualTo(String value) {
            addCriterion("auth_id <>", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThan(String value) {
            addCriterion("auth_id >", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThanOrEqualTo(String value) {
            addCriterion("auth_id >=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThan(String value) {
            addCriterion("auth_id <", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThanOrEqualTo(String value) {
            addCriterion("auth_id <=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLike(String value) {
            addCriterion("auth_id like", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotLike(String value) {
            addCriterion("auth_id not like", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdIn(List<String> values) {
            addCriterion("auth_id in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotIn(List<String> values) {
            addCriterion("auth_id not in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdBetween(String value1, String value2) {
            addCriterion("auth_id between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotBetween(String value1, String value2) {
            addCriterion("auth_id not between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthNameIsNull() {
            addCriterion("auth_name is null");
            return (Criteria) this;
        }

        public Criteria andAuthNameIsNotNull() {
            addCriterion("auth_name is not null");
            return (Criteria) this;
        }

        public Criteria andAuthNameEqualTo(String value) {
            addCriterion("auth_name =", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameNotEqualTo(String value) {
            addCriterion("auth_name <>", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameGreaterThan(String value) {
            addCriterion("auth_name >", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameGreaterThanOrEqualTo(String value) {
            addCriterion("auth_name >=", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameLessThan(String value) {
            addCriterion("auth_name <", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameLessThanOrEqualTo(String value) {
            addCriterion("auth_name <=", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameLike(String value) {
            addCriterion("auth_name like", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameNotLike(String value) {
            addCriterion("auth_name not like", value, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameIn(List<String> values) {
            addCriterion("auth_name in", values, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameNotIn(List<String> values) {
            addCriterion("auth_name not in", values, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameBetween(String value1, String value2) {
            addCriterion("auth_name between", value1, value2, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthNameNotBetween(String value1, String value2) {
            addCriterion("auth_name not between", value1, value2, "authName");
            return (Criteria) this;
        }

        public Criteria andAuthPathIsNull() {
            addCriterion("auth_path is null");
            return (Criteria) this;
        }

        public Criteria andAuthPathIsNotNull() {
            addCriterion("auth_path is not null");
            return (Criteria) this;
        }

        public Criteria andAuthPathEqualTo(String value) {
            addCriterion("auth_path =", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathNotEqualTo(String value) {
            addCriterion("auth_path <>", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathGreaterThan(String value) {
            addCriterion("auth_path >", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathGreaterThanOrEqualTo(String value) {
            addCriterion("auth_path >=", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathLessThan(String value) {
            addCriterion("auth_path <", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathLessThanOrEqualTo(String value) {
            addCriterion("auth_path <=", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathLike(String value) {
            addCriterion("auth_path like", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathNotLike(String value) {
            addCriterion("auth_path not like", value, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathIn(List<String> values) {
            addCriterion("auth_path in", values, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathNotIn(List<String> values) {
            addCriterion("auth_path not in", values, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathBetween(String value1, String value2) {
            addCriterion("auth_path between", value1, value2, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthPathNotBetween(String value1, String value2) {
            addCriterion("auth_path not between", value1, value2, "authPath");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNull() {
            addCriterion("auth_code is null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNotNull() {
            addCriterion("auth_code is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeEqualTo(String value) {
            addCriterion("auth_code =", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotEqualTo(String value) {
            addCriterion("auth_code <>", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThan(String value) {
            addCriterion("auth_code >", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThanOrEqualTo(String value) {
            addCriterion("auth_code >=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThan(String value) {
            addCriterion("auth_code <", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThanOrEqualTo(String value) {
            addCriterion("auth_code <=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLike(String value) {
            addCriterion("auth_code like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotLike(String value) {
            addCriterion("auth_code not like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIn(List<String> values) {
            addCriterion("auth_code in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotIn(List<String> values) {
            addCriterion("auth_code not in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeBetween(String value1, String value2) {
            addCriterion("auth_code between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotBetween(String value1, String value2) {
            addCriterion("auth_code not between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthDiscIsNull() {
            addCriterion("auth_disc is null");
            return (Criteria) this;
        }

        public Criteria andAuthDiscIsNotNull() {
            addCriterion("auth_disc is not null");
            return (Criteria) this;
        }

        public Criteria andAuthDiscEqualTo(String value) {
            addCriterion("auth_disc =", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscNotEqualTo(String value) {
            addCriterion("auth_disc <>", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscGreaterThan(String value) {
            addCriterion("auth_disc >", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscGreaterThanOrEqualTo(String value) {
            addCriterion("auth_disc >=", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscLessThan(String value) {
            addCriterion("auth_disc <", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscLessThanOrEqualTo(String value) {
            addCriterion("auth_disc <=", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscLike(String value) {
            addCriterion("auth_disc like", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscNotLike(String value) {
            addCriterion("auth_disc not like", value, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscIn(List<String> values) {
            addCriterion("auth_disc in", values, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscNotIn(List<String> values) {
            addCriterion("auth_disc not in", values, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscBetween(String value1, String value2) {
            addCriterion("auth_disc between", value1, value2, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthDiscNotBetween(String value1, String value2) {
            addCriterion("auth_disc not between", value1, value2, "authDisc");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandIsNull() {
            addCriterion("auth_shorthand is null");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandIsNotNull() {
            addCriterion("auth_shorthand is not null");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandEqualTo(String value) {
            addCriterion("auth_shorthand =", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandNotEqualTo(String value) {
            addCriterion("auth_shorthand <>", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandGreaterThan(String value) {
            addCriterion("auth_shorthand >", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandGreaterThanOrEqualTo(String value) {
            addCriterion("auth_shorthand >=", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandLessThan(String value) {
            addCriterion("auth_shorthand <", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandLessThanOrEqualTo(String value) {
            addCriterion("auth_shorthand <=", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandLike(String value) {
            addCriterion("auth_shorthand like", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandNotLike(String value) {
            addCriterion("auth_shorthand not like", value, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandIn(List<String> values) {
            addCriterion("auth_shorthand in", values, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandNotIn(List<String> values) {
            addCriterion("auth_shorthand not in", values, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandBetween(String value1, String value2) {
            addCriterion("auth_shorthand between", value1, value2, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShorthandNotBetween(String value1, String value2) {
            addCriterion("auth_shorthand not between", value1, value2, "authShorthand");
            return (Criteria) this;
        }

        public Criteria andAuthShIsNull() {
            addCriterion("auth_sh is null");
            return (Criteria) this;
        }

        public Criteria andAuthShIsNotNull() {
            addCriterion("auth_sh is not null");
            return (Criteria) this;
        }

        public Criteria andAuthShEqualTo(String value) {
            addCriterion("auth_sh =", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShNotEqualTo(String value) {
            addCriterion("auth_sh <>", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShGreaterThan(String value) {
            addCriterion("auth_sh >", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShGreaterThanOrEqualTo(String value) {
            addCriterion("auth_sh >=", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShLessThan(String value) {
            addCriterion("auth_sh <", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShLessThanOrEqualTo(String value) {
            addCriterion("auth_sh <=", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShLike(String value) {
            addCriterion("auth_sh like", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShNotLike(String value) {
            addCriterion("auth_sh not like", value, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShIn(List<String> values) {
            addCriterion("auth_sh in", values, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShNotIn(List<String> values) {
            addCriterion("auth_sh not in", values, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShBetween(String value1, String value2) {
            addCriterion("auth_sh between", value1, value2, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthShNotBetween(String value1, String value2) {
            addCriterion("auth_sh not between", value1, value2, "authSh");
            return (Criteria) this;
        }

        public Criteria andAuthAdIsNull() {
            addCriterion("auth_ad is null");
            return (Criteria) this;
        }

        public Criteria andAuthAdIsNotNull() {
            addCriterion("auth_ad is not null");
            return (Criteria) this;
        }

        public Criteria andAuthAdEqualTo(String value) {
            addCriterion("auth_ad =", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdNotEqualTo(String value) {
            addCriterion("auth_ad <>", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdGreaterThan(String value) {
            addCriterion("auth_ad >", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdGreaterThanOrEqualTo(String value) {
            addCriterion("auth_ad >=", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdLessThan(String value) {
            addCriterion("auth_ad <", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdLessThanOrEqualTo(String value) {
            addCriterion("auth_ad <=", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdLike(String value) {
            addCriterion("auth_ad like", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdNotLike(String value) {
            addCriterion("auth_ad not like", value, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdIn(List<String> values) {
            addCriterion("auth_ad in", values, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdNotIn(List<String> values) {
            addCriterion("auth_ad not in", values, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdBetween(String value1, String value2) {
            addCriterion("auth_ad between", value1, value2, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthAdNotBetween(String value1, String value2) {
            addCriterion("auth_ad not between", value1, value2, "authAd");
            return (Criteria) this;
        }

        public Criteria andAuthRmIsNull() {
            addCriterion("auth_rm is null");
            return (Criteria) this;
        }

        public Criteria andAuthRmIsNotNull() {
            addCriterion("auth_rm is not null");
            return (Criteria) this;
        }

        public Criteria andAuthRmEqualTo(String value) {
            addCriterion("auth_rm =", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmNotEqualTo(String value) {
            addCriterion("auth_rm <>", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmGreaterThan(String value) {
            addCriterion("auth_rm >", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmGreaterThanOrEqualTo(String value) {
            addCriterion("auth_rm >=", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmLessThan(String value) {
            addCriterion("auth_rm <", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmLessThanOrEqualTo(String value) {
            addCriterion("auth_rm <=", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmLike(String value) {
            addCriterion("auth_rm like", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmNotLike(String value) {
            addCriterion("auth_rm not like", value, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmIn(List<String> values) {
            addCriterion("auth_rm in", values, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmNotIn(List<String> values) {
            addCriterion("auth_rm not in", values, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmBetween(String value1, String value2) {
            addCriterion("auth_rm between", value1, value2, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthRmNotBetween(String value1, String value2) {
            addCriterion("auth_rm not between", value1, value2, "authRm");
            return (Criteria) this;
        }

        public Criteria andAuthMdIsNull() {
            addCriterion("auth_md is null");
            return (Criteria) this;
        }

        public Criteria andAuthMdIsNotNull() {
            addCriterion("auth_md is not null");
            return (Criteria) this;
        }

        public Criteria andAuthMdEqualTo(String value) {
            addCriterion("auth_md =", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdNotEqualTo(String value) {
            addCriterion("auth_md <>", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdGreaterThan(String value) {
            addCriterion("auth_md >", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdGreaterThanOrEqualTo(String value) {
            addCriterion("auth_md >=", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdLessThan(String value) {
            addCriterion("auth_md <", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdLessThanOrEqualTo(String value) {
            addCriterion("auth_md <=", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdLike(String value) {
            addCriterion("auth_md like", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdNotLike(String value) {
            addCriterion("auth_md not like", value, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdIn(List<String> values) {
            addCriterion("auth_md in", values, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdNotIn(List<String> values) {
            addCriterion("auth_md not in", values, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdBetween(String value1, String value2) {
            addCriterion("auth_md between", value1, value2, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthMdNotBetween(String value1, String value2) {
            addCriterion("auth_md not between", value1, value2, "authMd");
            return (Criteria) this;
        }

        public Criteria andAuthSeIsNull() {
            addCriterion("auth_se is null");
            return (Criteria) this;
        }

        public Criteria andAuthSeIsNotNull() {
            addCriterion("auth_se is not null");
            return (Criteria) this;
        }

        public Criteria andAuthSeEqualTo(String value) {
            addCriterion("auth_se =", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeNotEqualTo(String value) {
            addCriterion("auth_se <>", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeGreaterThan(String value) {
            addCriterion("auth_se >", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeGreaterThanOrEqualTo(String value) {
            addCriterion("auth_se >=", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeLessThan(String value) {
            addCriterion("auth_se <", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeLessThanOrEqualTo(String value) {
            addCriterion("auth_se <=", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeLike(String value) {
            addCriterion("auth_se like", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeNotLike(String value) {
            addCriterion("auth_se not like", value, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeIn(List<String> values) {
            addCriterion("auth_se in", values, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeNotIn(List<String> values) {
            addCriterion("auth_se not in", values, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeBetween(String value1, String value2) {
            addCriterion("auth_se between", value1, value2, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthSeNotBetween(String value1, String value2) {
            addCriterion("auth_se not between", value1, value2, "authSe");
            return (Criteria) this;
        }

        public Criteria andAuthImIsNull() {
            addCriterion("auth_im is null");
            return (Criteria) this;
        }

        public Criteria andAuthImIsNotNull() {
            addCriterion("auth_im is not null");
            return (Criteria) this;
        }

        public Criteria andAuthImEqualTo(String value) {
            addCriterion("auth_im =", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImNotEqualTo(String value) {
            addCriterion("auth_im <>", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImGreaterThan(String value) {
            addCriterion("auth_im >", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImGreaterThanOrEqualTo(String value) {
            addCriterion("auth_im >=", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImLessThan(String value) {
            addCriterion("auth_im <", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImLessThanOrEqualTo(String value) {
            addCriterion("auth_im <=", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImLike(String value) {
            addCriterion("auth_im like", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImNotLike(String value) {
            addCriterion("auth_im not like", value, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImIn(List<String> values) {
            addCriterion("auth_im in", values, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImNotIn(List<String> values) {
            addCriterion("auth_im not in", values, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImBetween(String value1, String value2) {
            addCriterion("auth_im between", value1, value2, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthImNotBetween(String value1, String value2) {
            addCriterion("auth_im not between", value1, value2, "authIm");
            return (Criteria) this;
        }

        public Criteria andAuthExIsNull() {
            addCriterion("auth_ex is null");
            return (Criteria) this;
        }

        public Criteria andAuthExIsNotNull() {
            addCriterion("auth_ex is not null");
            return (Criteria) this;
        }

        public Criteria andAuthExEqualTo(String value) {
            addCriterion("auth_ex =", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExNotEqualTo(String value) {
            addCriterion("auth_ex <>", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExGreaterThan(String value) {
            addCriterion("auth_ex >", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExGreaterThanOrEqualTo(String value) {
            addCriterion("auth_ex >=", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExLessThan(String value) {
            addCriterion("auth_ex <", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExLessThanOrEqualTo(String value) {
            addCriterion("auth_ex <=", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExLike(String value) {
            addCriterion("auth_ex like", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExNotLike(String value) {
            addCriterion("auth_ex not like", value, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExIn(List<String> values) {
            addCriterion("auth_ex in", values, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExNotIn(List<String> values) {
            addCriterion("auth_ex not in", values, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExBetween(String value1, String value2) {
            addCriterion("auth_ex between", value1, value2, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthExNotBetween(String value1, String value2) {
            addCriterion("auth_ex not between", value1, value2, "authEx");
            return (Criteria) this;
        }

        public Criteria andAuthPrIsNull() {
            addCriterion("auth_pr is null");
            return (Criteria) this;
        }

        public Criteria andAuthPrIsNotNull() {
            addCriterion("auth_pr is not null");
            return (Criteria) this;
        }

        public Criteria andAuthPrEqualTo(String value) {
            addCriterion("auth_pr =", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrNotEqualTo(String value) {
            addCriterion("auth_pr <>", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrGreaterThan(String value) {
            addCriterion("auth_pr >", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrGreaterThanOrEqualTo(String value) {
            addCriterion("auth_pr >=", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrLessThan(String value) {
            addCriterion("auth_pr <", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrLessThanOrEqualTo(String value) {
            addCriterion("auth_pr <=", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrLike(String value) {
            addCriterion("auth_pr like", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrNotLike(String value) {
            addCriterion("auth_pr not like", value, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrIn(List<String> values) {
            addCriterion("auth_pr in", values, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrNotIn(List<String> values) {
            addCriterion("auth_pr not in", values, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrBetween(String value1, String value2) {
            addCriterion("auth_pr between", value1, value2, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthPrNotBetween(String value1, String value2) {
            addCriterion("auth_pr not between", value1, value2, "authPr");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagIsNull() {
            addCriterion("auth_dis_flag is null");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagIsNotNull() {
            addCriterion("auth_dis_flag is not null");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagEqualTo(String value) {
            addCriterion("auth_dis_flag =", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagNotEqualTo(String value) {
            addCriterion("auth_dis_flag <>", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagGreaterThan(String value) {
            addCriterion("auth_dis_flag >", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagGreaterThanOrEqualTo(String value) {
            addCriterion("auth_dis_flag >=", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagLessThan(String value) {
            addCriterion("auth_dis_flag <", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagLessThanOrEqualTo(String value) {
            addCriterion("auth_dis_flag <=", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagLike(String value) {
            addCriterion("auth_dis_flag like", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagNotLike(String value) {
            addCriterion("auth_dis_flag not like", value, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagIn(List<String> values) {
            addCriterion("auth_dis_flag in", values, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagNotIn(List<String> values) {
            addCriterion("auth_dis_flag not in", values, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagBetween(String value1, String value2) {
            addCriterion("auth_dis_flag between", value1, value2, "authDisFlag");
            return (Criteria) this;
        }

        public Criteria andAuthDisFlagNotBetween(String value1, String value2) {
            addCriterion("auth_dis_flag not between", value1, value2, "authDisFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_auth
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}