package com.service.domain;

public class RoleAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role_auth.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role_auth.auth_id
     *
     * @mbggenerated
     */
    private String authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role_auth.role_id
     *
     * @return the value of tab_role_auth.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role_auth.role_id
     *
     * @param roleId the value for tab_role_auth.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role_auth.auth_id
     *
     * @return the value of tab_role_auth.auth_id
     *
     * @mbggenerated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role_auth.auth_id
     *
     * @param authId the value for tab_role_auth.auth_id
     *
     * @mbggenerated
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role_auth
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleAuth other = (RoleAuth) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getAuthId() == null ? other.getAuthId() == null : this.getAuthId().equals(other.getAuthId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role_auth
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getAuthId() == null) ? 0 : getAuthId().hashCode());
        return result;
    }
}