package com.service.domain;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.role_disc
     *
     * @mbggenerated
     */
    private String roleDisc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.role_dis_flag
     *
     * @mbggenerated
     */
    private String roleDisFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.role_id
     *
     * @return the value of tab_role.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.role_id
     *
     * @param roleId the value for tab_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.role_name
     *
     * @return the value of tab_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.role_name
     *
     * @param roleName the value for tab_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.role_disc
     *
     * @return the value of tab_role.role_disc
     *
     * @mbggenerated
     */
    public String getRoleDisc() {
        return roleDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.role_disc
     *
     * @param roleDisc the value for tab_role.role_disc
     *
     * @mbggenerated
     */
    public void setRoleDisc(String roleDisc) {
        this.roleDisc = roleDisc == null ? null : roleDisc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.role_dis_flag
     *
     * @return the value of tab_role.role_dis_flag
     *
     * @mbggenerated
     */
    public String getRoleDisFlag() {
        return roleDisFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.role_dis_flag
     *
     * @param roleDisFlag the value for tab_role.role_dis_flag
     *
     * @mbggenerated
     */
    public void setRoleDisFlag(String roleDisFlag) {
        this.roleDisFlag = roleDisFlag == null ? null : roleDisFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getRoleDisc() == null ? other.getRoleDisc() == null : this.getRoleDisc().equals(other.getRoleDisc()))
            && (this.getRoleDisFlag() == null ? other.getRoleDisFlag() == null : this.getRoleDisFlag().equals(other.getRoleDisFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getRoleDisc() == null) ? 0 : getRoleDisc().hashCode());
        result = prime * result + ((getRoleDisFlag() == null) ? 0 : getRoleDisFlag().hashCode());
        return result;
    }
}