package com.service.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_real_name
     *
     * @mbggenerated
     */
    private String userRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_level
     *
     * @mbggenerated
     */
    private String userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_job
     *
     * @mbggenerated
     */
    private String userJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_gender
     *
     * @mbggenerated
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_tel
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_qq
     *
     * @mbggenerated
     */
    private String userQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_onBoard_time
     *
     * @mbggenerated
     */
    private String userOnboardTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_last_login_time
     *
     * @mbggenerated
     */
    private String userLastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.user_visit_times
     *
     * @mbggenerated
     */
    private Integer userVisitTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_no
     *
     * @return the value of tab_user.user_no
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_no
     *
     * @param userNo the value for tab_user.user_no
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_real_name
     *
     * @return the value of tab_user.user_real_name
     *
     * @mbggenerated
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_real_name
     *
     * @param userRealName the value for tab_user.user_real_name
     *
     * @mbggenerated
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName == null ? null : userRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_email
     *
     * @return the value of tab_user.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_email
     *
     * @param userEmail the value for tab_user.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_password
     *
     * @return the value of tab_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_password
     *
     * @param userPassword the value for tab_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_level
     *
     * @return the value of tab_user.user_level
     *
     * @mbggenerated
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_level
     *
     * @param userLevel the value for tab_user.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel == null ? null : userLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_name
     *
     * @return the value of tab_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_name
     *
     * @param userName the value for tab_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_job
     *
     * @return the value of tab_user.user_job
     *
     * @mbggenerated
     */
    public String getUserJob() {
        return userJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_job
     *
     * @param userJob the value for tab_user.user_job
     *
     * @mbggenerated
     */
    public void setUserJob(String userJob) {
        this.userJob = userJob == null ? null : userJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_gender
     *
     * @return the value of tab_user.user_gender
     *
     * @mbggenerated
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_gender
     *
     * @param userGender the value for tab_user.user_gender
     *
     * @mbggenerated
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_tel
     *
     * @return the value of tab_user.user_tel
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_tel
     *
     * @param userTel the value for tab_user.user_tel
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_qq
     *
     * @return the value of tab_user.user_qq
     *
     * @mbggenerated
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_qq
     *
     * @param userQq the value for tab_user.user_qq
     *
     * @mbggenerated
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq == null ? null : userQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_onBoard_time
     *
     * @return the value of tab_user.user_onBoard_time
     *
     * @mbggenerated
     */
    public String getUserOnboardTime() {
        return userOnboardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_onBoard_time
     *
     * @param userOnboardTime the value for tab_user.user_onBoard_time
     *
     * @mbggenerated
     */
    public void setUserOnboardTime(String userOnboardTime) {
        this.userOnboardTime = userOnboardTime == null ? null : userOnboardTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_last_login_time
     *
     * @return the value of tab_user.user_last_login_time
     *
     * @mbggenerated
     */
    public String getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_last_login_time
     *
     * @param userLastLoginTime the value for tab_user.user_last_login_time
     *
     * @mbggenerated
     */
    public void setUserLastLoginTime(String userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime == null ? null : userLastLoginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.user_visit_times
     *
     * @return the value of tab_user.user_visit_times
     *
     * @mbggenerated
     */
    public Integer getUserVisitTimes() {
        return userVisitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.user_visit_times
     *
     * @param userVisitTimes the value for tab_user.user_visit_times
     *
     * @mbggenerated
     */
    public void setUserVisitTimes(Integer userVisitTimes) {
        this.userVisitTimes = userVisitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
            && (this.getUserRealName() == null ? other.getUserRealName() == null : this.getUserRealName().equals(other.getUserRealName()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserPassword() == null ? other.getUserPassword() == null : this.getUserPassword().equals(other.getUserPassword()))
            && (this.getUserLevel() == null ? other.getUserLevel() == null : this.getUserLevel().equals(other.getUserLevel()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserJob() == null ? other.getUserJob() == null : this.getUserJob().equals(other.getUserJob()))
            && (this.getUserGender() == null ? other.getUserGender() == null : this.getUserGender().equals(other.getUserGender()))
            && (this.getUserTel() == null ? other.getUserTel() == null : this.getUserTel().equals(other.getUserTel()))
            && (this.getUserQq() == null ? other.getUserQq() == null : this.getUserQq().equals(other.getUserQq()))
            && (this.getUserOnboardTime() == null ? other.getUserOnboardTime() == null : this.getUserOnboardTime().equals(other.getUserOnboardTime()))
            && (this.getUserLastLoginTime() == null ? other.getUserLastLoginTime() == null : this.getUserLastLoginTime().equals(other.getUserLastLoginTime()))
            && (this.getUserVisitTimes() == null ? other.getUserVisitTimes() == null : this.getUserVisitTimes().equals(other.getUserVisitTimes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getUserRealName() == null) ? 0 : getUserRealName().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
        result = prime * result + ((getUserLevel() == null) ? 0 : getUserLevel().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserJob() == null) ? 0 : getUserJob().hashCode());
        result = prime * result + ((getUserGender() == null) ? 0 : getUserGender().hashCode());
        result = prime * result + ((getUserTel() == null) ? 0 : getUserTel().hashCode());
        result = prime * result + ((getUserQq() == null) ? 0 : getUserQq().hashCode());
        result = prime * result + ((getUserOnboardTime() == null) ? 0 : getUserOnboardTime().hashCode());
        result = prime * result + ((getUserLastLoginTime() == null) ? 0 : getUserLastLoginTime().hashCode());
        result = prime * result + ((getUserVisitTimes() == null) ? 0 : getUserVisitTimes().hashCode());
        return result;
    }
}