/******************************************************************
 *
 *    Java Lib For Android, Powered By Shenzhen Jiuzhou.
 *
 *    Copyright (c) 2001-2014 Digital Telemedia Co.,Ltd
 *    http://www.d-telemedia.com/
 *
 *    Package:     net.youhj.service
 *
 *    Filename:    AuthService.java
 *
 *    Description: TODO(用一句话描述该文件做什么)
 *
 *    Copyright:   Copyright (c) 2001-2014
 *
 *    Company:     Digital Telemedia Co.,Ltd
 *
 *    @author:     lightSmart
 *
 *    @version:    1.0.0
 *
 *    Create at:   2017年2月28日 下午3:36:58
 *
 *    Revision:
 *
 *    2017年2月28日 下午3:36:58
 *        - first revision
 *
 *****************************************************************/
package com.service.service;

import com.service.domain.Auth;
import com.servicew.domain.AuthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @ClassName AuthService
 * @Description TODO(这里用一句话描述这个类的作用)
 * @author lightSmart
 * @Date 2017年2月28日 下午3:36:58
 * @version 1.0.0
 */
public interface AuthService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);
}
