/******************************************************************
 *
 *    Java Lib For Android, Powered By Shenzhen Jiuzhou.
 *
 *    Copyright (c) 2001-2014 Digital Telemedia Co.,Ltd
 *    http://www.d-telemedia.com/
 *
 *    Package:     net.youhj.service
 *
 *    Filename:    ResService.java
 *
 *    Description: TODO(用一句话描述该文件做什么)
 *
 *    Copyright:   Copyright (c) 2001-2014
 *
 *    Company:     Digital Telemedia Co.,Ltd
 *
 *    @author:     lightSmart
 *
 *    @version:    1.0.0
 *
 *    Create at:   2017年2月28日 下午3:37:11
 *
 *    Revision:
 *
 *    2017年2月28日 下午3:37:11
 *        - first revision
 *
 *****************************************************************/
package com.service.service;

import com.service.domain.Res;
import com.service.domain.ResExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @ClassName ResService
 * @Description TODO(这里用一句话描述这个类的作用)
 * @author lightSmart
 * @Date 2017年2月28日 下午3:37:11
 * @version 1.0.0
 */
public interface ResService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int countByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int deleteByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int insert(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int insertSelective(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    List<Res> selectByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Res record, @Param("example") ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_res
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Res record, @Param("example") ResExample example);
}
