package com.service.mapper;

import com.service.domain.Auth;
import com.service.domain.AuthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);
}